import jsPDF from "jspdf";

const DARK_BLUE = [15, 23, 42];
const WHITE = [255, 255, 255];
const PRIMARY = [59, 130, 246];
const RED = [239, 68, 68];
const GREEN = [34, 197, 94];
const AMBER = [245, 158, 11];
const GRAY = [148, 163, 184];

function drawHeader(doc: jsPDF, pageNum: number, totalPages: number) {
  doc.setFillColor(...DARK_BLUE);
  doc.rect(0, 0, 210, 22, "F");
  doc.setTextColor(...WHITE);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("VERIASTRA", 14, 14);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.text("Identity Verification & Deepfake Defense", 50, 14);

  // Footer
  doc.setFillColor(240, 240, 245);
  doc.rect(0, 275, 210, 22, "F");
  doc.setTextColor(...GRAY);
  doc.setFontSize(7);
  doc.text("CONFIDENTIAL", 14, 284);
  doc.text(`Page ${pageNum} of ${totalPages}`, 180, 284);
}

function drawShield(doc: jsPDF, x: number, y: number, size: number) {
  doc.setDrawColor(...PRIMARY);
  doc.setLineWidth(1.5);
  // Simple shield shape
  doc.setFillColor(...PRIMARY);
  doc.circle(x, y, size * 0.4, "F");
  doc.setTextColor(...WHITE);
  doc.setFontSize(size * 0.5);
  doc.setFont("helvetica", "bold");
  doc.text("✓", x - size * 0.12, y + size * 0.15);
}

export interface ReportData {
  verificationId: string;
  subjectName: string;
  riskScore: number;
  confidence: number;
  prediction: "REAL" | "FAKE";
  videoScore: number;
  audioScore: number;
  livenessScore: number;
  signals: { label: string; score: number; region: string; severity: string }[];
  reasonCodes: string[];
}

export function generateEvidenceReport(data: ReportData) {
  const doc = new jsPDF();
  const totalPages = 4;
  const date = new Date().toLocaleString();

  // ---- PAGE 1: Cover ----
  drawHeader(doc, 1, totalPages);
  
  drawShield(doc, 105, 60, 30);

  doc.setTextColor(...DARK_BLUE);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("Identity Verification", 105, 95, { align: "center" });
  doc.text("Evidence Report", 105, 105, { align: "center" });

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...GRAY);
  doc.text("Confidential — Generated by Veriastra AI Platform", 105, 118, { align: "center" });

  // Metadata box
  const mx = 40;
  const my = 135;
  doc.setFillColor(245, 247, 250);
  doc.roundedRect(mx, my, 130, 70, 3, 3, "F");
  doc.setDrawColor(200, 210, 220);
  doc.roundedRect(mx, my, 130, 70, 3, 3, "S");

  doc.setTextColor(...DARK_BLUE);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  const rows = [
    ["Session ID", data.verificationId],
    ["Subject", data.subjectName],
    ["Date", date],
    ["Verdict", data.prediction === "FAKE" ? "FAKE DETECTED" : "VERIFIED REAL"],
    ["Risk Score", `${data.riskScore}/100`],
    ["Confidence", `${data.confidence.toFixed(1)}%`],
  ];
  rows.forEach(([k, v], i) => {
    const ry = my + 10 + i * 10;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...GRAY);
    doc.text(k + ":", mx + 8, ry);
    doc.setFont("helvetica", "bold");
    if (k === "Verdict") {
      doc.setTextColor(...(data.prediction === "FAKE" ? RED : GREEN));
    } else {
      doc.setTextColor(...DARK_BLUE);
    }
    doc.text(v, mx + 50, ry);
  });

  // ---- PAGE 2: Risk Assessment ----
  doc.addPage();
  drawHeader(doc, 2, totalPages);

  doc.setTextColor(...DARK_BLUE);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Risk Assessment Summary", 14, 36);

  doc.setDrawColor(220, 225, 230);
  doc.line(14, 40, 196, 40);

  const metrics = [
    { label: "Video Authenticity", value: data.videoScore, status: data.videoScore < 40 ? "MANIPULATED" : "AUTHENTIC" },
    { label: "Audio Authenticity", value: data.audioScore, status: data.audioScore > 60 ? "AUTHENTIC" : "SUSPICIOUS" },
    { label: "Liveness Score", value: data.livenessScore, status: data.livenessScore < 40 ? "FAILED" : "PASSED" },
  ];

  metrics.forEach((m, i) => {
    const y = 55 + i * 28;
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...DARK_BLUE);
    doc.text(m.label, 14, y);

    doc.setFontSize(11);
    doc.text(`${m.value}%`, 120, y);

    const color = m.value < 40 ? RED : m.value < 60 ? AMBER : GREEN;
    doc.setTextColor(...color);
    doc.setFont("helvetica", "bold");
    doc.text(m.status, 145, y);

    // Progress bar
    doc.setFillColor(230, 235, 240);
    doc.roundedRect(14, y + 3, 180, 4, 2, 2, "F");
    doc.setFillColor(...color);
    doc.roundedRect(14, y + 3, (m.value / 100) * 180, 4, 2, 2, "F");
  });

  // Reason codes
  const rcy = 145;
  doc.setTextColor(...DARK_BLUE);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Reason Codes", 14, rcy);

  data.reasonCodes.forEach((code, i) => {
    doc.setFillColor(254, 242, 242);
    doc.roundedRect(14, rcy + 6 + i * 12, 180, 10, 2, 2, "F");
    doc.setTextColor(...RED);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text(code, 18, rcy + 13 + i * 12);
  });

  // Recommendation
  const recy = rcy + 10 + data.reasonCodes.length * 12 + 15;
  doc.setFillColor(254, 249, 235);
  doc.roundedRect(14, recy, 180, 16, 3, 3, "F");
  doc.setDrawColor(...AMBER);
  doc.roundedRect(14, recy, 180, 16, 3, 3, "S");
  doc.setTextColor(...AMBER);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("RECOMMENDATION: ESCALATE FOR MANUAL REVIEW", 20, recy + 10);

  // ---- PAGE 3: Detection Signals ----
  doc.addPage();
  drawHeader(doc, 3, totalPages);

  doc.setTextColor(...DARK_BLUE);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Detection Signals", 14, 36);
  doc.line(14, 40, 196, 40);

  // Table header
  const th = 50;
  doc.setFillColor(...DARK_BLUE);
  doc.rect(14, th, 182, 10, "F");
  doc.setTextColor(...WHITE);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text("SIGNAL", 18, th + 7);
  doc.text("CONFIDENCE", 90, th + 7);
  doc.text("REGION", 130, th + 7);
  doc.text("SEVERITY", 168, th + 7);

  data.signals.forEach((s, i) => {
    const y = th + 12 + i * 14;
    doc.setFillColor(i % 2 === 0 ? 248 : 255, i % 2 === 0 ? 250 : 255, i % 2 === 0 ? 252 : 255);
    doc.rect(14, y - 2, 182, 14, "F");

    doc.setTextColor(...DARK_BLUE);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(s.label, 18, y + 6);

    doc.setFont("helvetica", "bold");
    doc.text(`${s.score}%`, 94, y + 6);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(...GRAY);
    doc.text(s.region, 134, y + 6);

    const sevColor = s.severity === "HIGH" ? RED : AMBER;
    doc.setTextColor(...sevColor);
    doc.setFont("helvetica", "bold");
    doc.text(s.severity, 172, y + 6);
  });

  const modelY = th + 16 + data.signals.length * 14 + 10;
  doc.setTextColor(...GRAY);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("Model Version: veriastra-fusion-v2.1.0  |  Processing Time: 1,340ms", 14, modelY);

  // ---- PAGE 4: Provenance ----
  doc.addPage();
  drawHeader(doc, 4, totalPages);

  doc.setTextColor(...DARK_BLUE);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Provenance & Audit Trail", 14, 36);
  doc.line(14, 40, 196, 40);

  const events = [
    { time: "T+0ms", event: "Capture received", status: "✓ Complete" },
    { time: "T+120ms", event: "Pre-processing (face detection, normalization)", status: "✓ Complete" },
    { time: "T+340ms", event: "Model inference — video deepfake detection", status: "✓ Complete" },
    { time: "T+680ms", event: "Model inference — audio analysis", status: "✓ Complete" },
    { time: "T+890ms", event: "Liveness verification check", status: "✓ Complete" },
    { time: "T+1120ms", event: "Evidence pack generation", status: "✓ Complete" },
    { time: "T+1340ms", event: "Report generated", status: "✓ Complete" },
  ];

  // Timeline table
  const tth = 50;
  doc.setFillColor(...DARK_BLUE);
  doc.rect(14, tth, 182, 10, "F");
  doc.setTextColor(...WHITE);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text("TIMESTAMP", 18, tth + 7);
  doc.text("EVENT", 58, tth + 7);
  doc.text("STATUS", 168, tth + 7);

  events.forEach((e, i) => {
    const y = tth + 12 + i * 12;
    doc.setFillColor(i % 2 === 0 ? 248 : 255, i % 2 === 0 ? 250 : 255, i % 2 === 0 ? 252 : 255);
    doc.rect(14, y - 2, 182, 12, "F");

    doc.setTextColor(...DARK_BLUE);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.text(e.time, 18, y + 5);

    doc.setFont("helvetica", "normal");
    doc.text(e.event, 58, y + 5);

    doc.setTextColor(...GREEN);
    doc.setFont("helvetica", "bold");
    doc.text(e.status, 168, y + 5);
  });

  // Hash
  const hashY = tth + 16 + events.length * 12 + 15;
  doc.setFillColor(245, 247, 250);
  doc.roundedRect(14, hashY, 182, 20, 3, 3, "F");
  doc.setTextColor(...GRAY);
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  const hash = Array.from({ length: 64 }, () => "0123456789abcdef"[Math.floor(Math.random() * 16)]).join("");
  doc.text(`Evidence Hash: sha256:${hash}`, 18, hashY + 8);
  doc.text("Signed by: Veriastra Verification Authority", 18, hashY + 15);

  // Legal footer
  doc.setTextColor(...GRAY);
  doc.setFontSize(7);
  doc.text("This report was generated automatically by Veriastra AI. For legal proceedings, contact legal@veriastra.ai", 14, 260);

  // Save
  const filename = `Veriastra_Report_${data.verificationId}_${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}

// Default report for dashboard demo
export function generateDefaultReport() {
  generateEvidenceReport({
    verificationId: "VRF-2846",
    subjectName: "Marcus Johnson",
    riskScore: 78,
    confidence: 93.2,
    prediction: "FAKE",
    videoScore: 2,
    audioScore: 87,
    livenessScore: 15,
    signals: [
      { label: "Facial Geometry Inconsistency", score: 96, region: "facial_geometry", severity: "HIGH" },
      { label: "Temporal Flickering", score: 82, region: "eye_region", severity: "HIGH" },
      { label: "Low Liveness Score", score: 78, region: "full_face", severity: "MEDIUM" },
      { label: "Audio-Visual Desync", score: 71, region: "lip_region", severity: "MEDIUM" },
    ],
    reasonCodes: ["low_liveness", "video_artifacts", "lip_sync_mismatch"],
  });
}

export function generateAnalyticsReport() {
  const doc = new jsPDF();
  
  // Header
  doc.setFillColor(...DARK_BLUE);
  doc.rect(0, 0, 210, 22, "F");
  doc.setTextColor(...WHITE);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("VERIASTRA — Security Analytics Report", 14, 14);

  doc.setTextColor(...DARK_BLUE);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Model Performance & Security Report", 14, 40);
  
  doc.setTextColor(...GRAY);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 48);

  // KPIs
  const kpis = [
    { label: "Detection Accuracy", value: "97.4%" },
    { label: "False Positive Rate", value: "1.2%" },
    { label: "False Negative Rate", value: "0.8%" },
    { label: "ROC-AUC", value: "0.992" },
    { label: "Daily Verifications", value: "12,843" },
    { label: "Avg Latency", value: "1.8s" },
  ];

  let y = 60;
  kpis.forEach((k, i) => {
    if (i % 2 === 0) {
      doc.setFillColor(245, 247, 250);
      doc.rect(14, y - 2, 182, 10, "F");
    }
    doc.setTextColor(...DARK_BLUE);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(k.label, 18, y + 5);
    doc.setFont("helvetica", "bold");
    doc.text(k.value, 140, y + 5);
    y += 10;
  });

  // Attack distribution
  y += 10;
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Attack Distribution", 14, y);
  y += 8;

  const attacks = [
    { type: "Face Swap", pct: "38%" },
    { type: "Voice Clone", pct: "24%" },
    { type: "Synthetic Video", pct: "21%" },
    { type: "Replay Attack", pct: "11%" },
    { type: "Mask Spoof", pct: "6%" },
  ];
  attacks.forEach((a) => {
    doc.setTextColor(...DARK_BLUE);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(`${a.type}: ${a.pct}`, 18, y);
    y += 8;
  });

  y += 10;
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Robustness Under Attack", 14, y);
  y += 8;

  const tests = [
    { test: "FaceSwap Deepfake", result: "Detected", confidence: "98%" },
    { test: "Voice Clone Attack", result: "Detected", confidence: "96%" },
    { test: "Replay Video", result: "Detected", confidence: "94%" },
    { test: "Mask Spoof", result: "Detected", confidence: "91%" },
    { test: "Real Human", result: "Passed", confidence: "99%" },
  ];
  tests.forEach((t) => {
    doc.setTextColor(...DARK_BLUE);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(`${t.test} — ${t.result} (${t.confidence})`, 18, y);
    y += 8;
  });

  // Footer
  doc.setFillColor(240, 240, 245);
  doc.rect(0, 275, 210, 22, "F");
  doc.setTextColor(...GRAY);
  doc.setFontSize(7);
  doc.text("CONFIDENTIAL — Veriastra AI Platform", 14, 284);

  doc.save(`Veriastra_Analytics_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
}
